### PR TITLE
Add ps:scale

### PR DESCRIPTION
**Pull request by fluke**
For #22 

@SebastianSzturo Tested this out by installing it with specific_install.

### CODE REVIEW

**Comment by SebastianSzturo** [comment]
Thanks for your contribution! I'll release a new version shortly.

**Comment by fluke** [comment]
@SebastianSzturo No problem. If you don't mind me asking, what's it like working at Shopify?

**Comment by SebastianSzturo** [comment]
It is a great journey for the last 2 years. 💪 
We are always looking for new talent -> https://www.shopify.com/careers

**Comment by fluke** [comment]
Ah nice. Doesn't look like there are opportunities in Bangalore right now.

**Pull request merged**
